version: '3'
services:
  my-app:
    build:
      context: .
    ports:
    - '8080:8080'
    volumes:
    - .:/app
    environment:
    # Chokidar, which Webpack uses for watching changes has an environment to force the use of polling: CHOKIDAR_USEPOLLING
    - CHOKIDAR_USEPOLLING=true